export const URL_CONFIG = {
    login: 'users/login',
    logout: 'logout',
    usersList: 'users/',
    rolesList: 'roles/',
    addRole: 'roles/addRole',
    updateRole: 'roles/',
    deleteRole: 'roles/deleteRole/',
    addUser: 'users/addUser',
    updateUser: 'users/',
    deleteUser: 'users/delete/',
    registerUser:'register',
    getInventory: 'inventory/',
    addInventory: 'inventory/add',
    deleteInventory: 'inventory/delete/',
    addnewBill: 'billing/add',
    getBillInfo: 'billing/',
    getAllTransactions: 'transactions/list/',
    getTransactionAmount:'analysis/transactionAmount',
    getInventoryQuant:'analysis/inventoryQuantity/',
    getCategorySales:'analysis/totalCategorySales',
    getTransactionCount:'analysis/totalTransactions'
}